import { h } from 'vue'
import type { ColumnDef } from '@tanstack/vue-table'

const warrantyBadgeVariant = (date: any) => {
  // Deine Logik für die Variante (z.B. 'destructive', 'outline', etc.)
  return 'outline'
}

export const data: any[] = [
  {
    "business_code": "NB",
    "asset_label": "NB-000001",
    "asset_sequence_number": 1,
    "category_id": 1,
    "status_definition_id": 1,
    "name": "Dell Latitude 5540",
    "description": "Notebook für Büroarbeitsplatz",
    "manufacturer_id": 1,
    "supplier_number": "SUP1001",
    "supplier_name": "Bechtle GmbH",
    "supplier_address": "Bechtle Platz 1",
    "supplier_post_code": "74172",
    "supplier_city": "Neckarsulm",
    "supplier_country": "Deutschland",
    "current_location_id": 1,
    "image_storage_key": "assets/nb-000001.jpg",
    "barcode_value": "100000001",
    "qr_value": "QR100000001",
    "purchase_value": 1299.99,
    "purchase_date": "2025-01-15",
    "purchase_document_guid": "doc-000001",
    "warranty_start_date": "2025-01-15",
    "warranty_end_date": "2028-01-14",
    "warranty_notify_days_before": 30
  },
  {
    "business_code": "NB",
    "asset_label": "NB-000002",
    "asset_sequence_number": 2,
    "category_id": 1,
    "status_definition_id": 1,
    "name": "Lenovo ThinkPad T14",
    "description": "Notebook Entwicklung",
    "manufacturer_id": 2,
    "supplier_number": "SUP1001",
    "supplier_name": "Bechtle GmbH",
    "supplier_address": "Bechtle Platz 1",
    "supplier_post_code": "74172",
    "supplier_city": "Neckarsulm",
    "supplier_country": "Deutschland",
    "current_location_id": 2,
    "image_storage_key": "assets/nb-000002.jpg",
    "barcode_value": "100000002",
    "qr_value": "QR100000002",
    "purchase_value": 1499.00,
    "purchase_date": "2024-08-12",
    "purchase_document_guid": "doc-000002",
    "warranty_start_date": "2024-08-12",
    "warranty_end_date": "2027-08-11",
    "warranty_notify_days_before": 30
  },
  {
    "business_code": "NB",
    "asset_label": "NB-000003",
    "asset_sequence_number": 3,
    "category_id": 1,
    "status_definition_id": 2,
    "name": "HP EliteBook 860",
    "description": "Notebook Vertrieb",
    "manufacturer_id": 3,
    "supplier_number": "SUP1001",
    "supplier_name": "Bechtle GmbH",
    "supplier_address": "Bechtle Platz 1",
    "supplier_post_code": "74172",
    "supplier_city": "Neckarsulm",
    "supplier_country": "Deutschland",
    "current_location_id": 3,
    "image_storage_key": "assets/nb-000003.jpg",
    "barcode_value": "100000003",
    "qr_value": "QR100000003",
    "purchase_value": 1399.00,
    "purchase_date": "2024-04-22",
    "purchase_document_guid": "doc-000003",
    "warranty_start_date": "2024-04-22",
    "warranty_end_date": "2027-04-21",
    "warranty_notify_days_before": 30
  },
  {
    "business_code": "MON",
    "asset_label": "MON-000004",
    "asset_sequence_number": 4,
    "category_id": 2,
    "status_definition_id": 1,
    "name": "Dell P2725H",
    "description": "27 Zoll Monitor",
    "manufacturer_id": 1,
    "supplier_number": "SUP1001",
    "supplier_name": "Bechtle GmbH",
    "supplier_address": "Bechtle Platz 1",
    "supplier_post_code": "74172",
    "supplier_city": "Neckarsulm",
    "supplier_country": "Deutschland",
    "current_location_id": 1,
    "image_storage_key": "assets/mon-000004.jpg",
    "barcode_value": "100000004",
    "qr_value": "QR100000004",
    "purchase_value": 289.90,
    "purchase_date": "2025-02-01",
    "purchase_document_guid": "doc-000004",
    "warranty_start_date": "2025-02-01",
    "warranty_end_date": "2028-01-31",
    "warranty_notify_days_before": 30
  },
  {
    "business_code": "MON",
    "asset_label": "MON-000005",
    "asset_sequence_number": 5,
    "category_id": 2,
    "status_definition_id": 1,
    "name": "Samsung S27A600",
    "description": "WQHD Monitor",
    "manufacturer_id": 4,
    "supplier_number": "SUP1001",
    "supplier_name": "Bechtle GmbH",
    "supplier_address": "Bechtle Platz 1",
    "supplier_post_code": "74172",
    "supplier_city": "Neckarsulm",
    "supplier_country": "Deutschland",
    "current_location_id": 1,
    "image_storage_key": "assets/mon-000005.jpg",
    "barcode_value": "100000005",
    "qr_value": "QR100000005",
    "purchase_value": 349.00,
    "purchase_date": "2025-03-18",
    "purchase_document_guid": "doc-000005",
    "warranty_start_date": "2025-03-18",
    "warranty_end_date": "2028-03-17",
    "warranty_notify_days_before": 30
  },
  {
    "business_code": "PHN",
    "asset_label": "PHN-000006",
    "asset_sequence_number": 6,
    "category_id": 3,
    "status_definition_id": 1,
    "name": "Apple iPhone 16",
    "description": "Firmenhandy",
    "manufacturer_id": 5,
    "supplier_number": "SUP1002",
    "supplier_name": "Telekom",
    "supplier_address": "Landgrabenweg 151",
    "supplier_post_code": "53227",
    "supplier_city": "Bonn",
    "supplier_country": "Deutschland",
    "current_location_id": 1,
    "image_storage_key": "assets/phn-000006.jpg",
    "barcode_value": "100000006",
    "qr_value": "QR100000006",
    "purchase_value": 1099.00,
    "purchase_date": "2025-01-08",
    "purchase_document_guid": "doc-000006",
    "warranty_start_date": "2025-01-08",
    "warranty_end_date": "2027-01-07",
    "warranty_notify_days_before": 60
  },
  {
    "business_code": "PHN",
    "asset_label": "PHN-000007",
    "asset_sequence_number": 7,
    "category_id": 3,
    "status_definition_id": 1,
    "name": "Samsung Galaxy S25",
    "description": "Android Smartphone",
    "manufacturer_id": 4,
    "supplier_number": "SUP1002",
    "supplier_name": "Telekom",
    "supplier_address": "Landgrabenweg 151",
    "supplier_post_code": "53227",
    "supplier_city": "Bonn",
    "supplier_country": "Deutschland",
    "current_location_id": 2,
    "image_storage_key": "assets/phn-000007.jpg",
    "barcode_value": "100000007",
    "qr_value": "QR100000007",
    "purchase_value": 899.00,
    "purchase_date": "2025-02-13",
    "purchase_document_guid": "doc-000007",
    "warranty_start_date": "2025-02-13",
    "warranty_end_date": "2027-02-12",
    "warranty_notify_days_before": 60
  },
  {
    "business_code": "TAB",
    "asset_label": "TAB-000008",
    "asset_sequence_number": 8,
    "category_id": 4,
    "status_definition_id": 1,
    "name": "iPad Air",
    "description": "Tablet Außendienst",
    "manufacturer_id": 5,
    "supplier_number": "SUP1002",
    "supplier_name": "Telekom",
    "supplier_address": "Landgrabenweg 151",
    "supplier_post_code": "53227",
    "supplier_city": "Bonn",
    "supplier_country": "Deutschland",
    "current_location_id": 3,
    "image_storage_key": "assets/tab-000008.jpg",
    "barcode_value": "100000008",
    "qr_value": "QR100000008",
    "purchase_value": 799.00,
    "purchase_date": "2025-02-20",
    "purchase_document_guid": "doc-000008",
    "warranty_start_date": "2025-02-20",
    "warranty_end_date": "2027-02-19",
    "warranty_notify_days_before": 30
  },
  {
    "business_code": "TAB",
    "asset_label": "TAB-000009",
    "asset_sequence_number": 9,
    "category_id": 4,
    "status_definition_id": 2,
    "name": "Samsung Galaxy Tab S10",
    "description": "Tablet Lager",
    "manufacturer_id": 4,
    "supplier_number": "SUP1002",
    "supplier_name": "Telekom",
    "supplier_address": "Landgrabenweg 151",
    "supplier_post_code": "53227",
    "supplier_city": "Bonn",
    "supplier_country": "Deutschland",
    "current_location_id": 4,
    "image_storage_key": "assets/tab-000009.jpg",
    "barcode_value": "100000009",
    "qr_value": "QR100000009",
    "purchase_value": 699.00,
    "purchase_date": "2024-11-10",
    "purchase_document_guid": "doc-000009",
    "warranty_start_date": "2024-11-10",
    "warranty_end_date": "2026-11-09",
    "warranty_notify_days_before": 30
  },
  {
    "business_code": "PRN",
    "asset_label": "PRN-000010",
    "asset_sequence_number": 10,
    "category_id": 5,
    "status_definition_id": 1,
    "name": "HP LaserJet Enterprise",
    "description": "Abteilungsdrucker",
    "manufacturer_id": 3,
    "supplier_number": "SUP1003",
    "supplier_name": "Cancom GmbH",
    "supplier_address": "Erika-Mann-Str. 69",
    "supplier_post_code": "80636",
    "supplier_city": "München",
    "supplier_country": "Deutschland",
    "current_location_id": 5,
    "image_storage_key": "assets/prn-000010.jpg",
    "barcode_value": "100000010",
    "qr_value": "QR100000010",
    "purchase_value": 1599.00,
    "purchase_date": "2024-09-01",
    "purchase_document_guid": "doc-000010",
    "warranty_start_date": "2024-09-01",
    "warranty_end_date": "2027-08-31",
    "warranty_notify_days_before": 90
  },
  {
    "business_code": "SRV",
    "asset_label": "SRV-000011",
    "asset_sequence_number": 11,
    "category_id": 6,
    "status_definition_id": 1,
    "name": "VMware Host 01",
    "description": "Produktionsserver",
    "manufacturer_id": 1,
    "supplier_number": "SUP1004",
    "supplier_name": "Dell Technologies",
    "supplier_address": "Unterschweinstiege 10",
    "supplier_post_code": "60549",
    "supplier_city": "Frankfurt",
    "supplier_country": "Deutschland",
    "current_location_id": 10,
    "image_storage_key": "assets/srv-000011.jpg",
    "barcode_value": "100000011",
    "qr_value": "QR100000011",
    "purchase_value": 9800.00,
    "purchase_date": "2024-01-20",
    "purchase_document_guid": "doc-000011",
    "warranty_start_date": "2024-01-20",
    "warranty_end_date": "2029-01-19",
    "warranty_notify_days_before": 120
  },
  {
    "business_code": "SRV",
    "asset_label": "SRV-000012",
    "asset_sequence_number": 12,
    "category_id": 6,
    "status_definition_id": 1,
    "name": "VMware Host 02",
    "description": "Cluster Node",
    "manufacturer_id": 1,
    "supplier_number": "SUP1004",
    "supplier_name": "Dell Technologies",
    "supplier_address": "Unterschweinstiege 10",
    "supplier_post_code": "60549",
    "supplier_city": "Frankfurt",
    "supplier_country": "Deutschland",
    "current_location_id": 10,
    "image_storage_key": "assets/srv-000012.jpg",
    "barcode_value": "100000012",
    "qr_value": "QR100000012",
    "purchase_value": 9800.00,
    "purchase_date": "2024-01-20",
    "purchase_document_guid": "doc-000012",
    "warranty_start_date": "2024-01-20",
    "warranty_end_date": "2029-01-19",
    "warranty_notify_days_before": 120
  },
  {
    "business_code": "NET",
    "asset_label": "NET-000013",
    "asset_sequence_number": 13,
    "category_id": 8,
    "status_definition_id": 1,
    "name": "Cisco Catalyst 9300",
    "description": "Core Switch",
    "manufacturer_id": 6,
    "supplier_number": "SUP1006",
    "supplier_name": "TD Synnex",
    "supplier_address": "Kistlerhofstraße 75",
    "supplier_post_code": "81379",
    "supplier_city": "München",
    "supplier_country": "Deutschland",
    "current_location_id": 10,
    "image_storage_key": "assets/net-000013.jpg",
    "barcode_value": "100000013",
    "qr_value": "QR100000013",
    "purchase_value": 4500.00,
    "purchase_date": "2024-06-15",
    "purchase_document_guid": "doc-000013",
    "warranty_start_date": "2024-06-15",
    "warranty_end_date": "2029-06-14",
    "warranty_notify_days_before": 120
  },

  {
    "business_code": "NET",
    "asset_label": "NET-000014",
    "asset_sequence_number": 14,
    "category_id": 8,
    "status_definition_id": 1,
    "name": "Fortinet FortiGate 200F",
    "description": "Firewall",
    "manufacturer_id": 7,
    "supplier_number": "SUP1006",
    "supplier_name": "TD Synnex",
    "supplier_address": "Kistlerhofstraße 75",
    "supplier_post_code": "81379",
    "supplier_city": "München",
    "supplier_country": "Deutschland",
    "current_location_id": 10,
    "image_storage_key": "assets/net-000014.jpg",
    "barcode_value": "100000014",
    "qr_value": "QR100000014",
    "purchase_value": 6200.00,
    "purchase_date": "2024-07-10",
    "purchase_document_guid": "doc-000014",
    "warranty_start_date": "2024-07-10",
    "warranty_end_date": "2029-07-09",
    "warranty_notify_days_before": 120
  },

  {
    "business_code": "SW",
    "asset_label": "SW-000015",
    "asset_sequence_number": 15,
    "category_id": 7,
    "status_definition_id": 1,
    "name": "Windows 11 Pro",
    "description": "Lizenz",
    "manufacturer_id": 8,
    "supplier_number": "SUP1005",
    "supplier_name": "Microsoft",
    "supplier_address": "Walter-Gropius-Str. 5",
    "supplier_post_code": "80807",
    "supplier_city": "München",
    "supplier_country": "Deutschland",
    "current_location_id": 1,
    "image_storage_key": "assets/sw-000015.jpg",
    "barcode_value": "100000015",
    "qr_value": "QR100000015",
    "purchase_value": 179.00,
    "purchase_date": "2025-01-01",
    "purchase_document_guid": "doc-000015",
    "warranty_start_date": null,
    "warranty_end_date": null,
    "warranty_notify_days_before": 0
  },

  {
    "business_code": "SW",
    "asset_label": "SW-000016",
    "asset_sequence_number": 16,
    "category_id": 7,
    "status_definition_id": 1,
    "name": "Microsoft Office 365 E3",
    "description": "Jahreslizenz",
    "manufacturer_id": 8,
    "supplier_number": "SUP1005",
    "supplier_name": "Microsoft",
    "supplier_address": "Walter-Gropius-Str. 5",
    "supplier_post_code": "80807",
    "supplier_city": "München",
    "supplier_country": "Deutschland",
    "current_location_id": 1,
    "image_storage_key": "assets/sw-000016.jpg",
    "barcode_value": "100000016",
    "qr_value": "QR100000016",
    "purchase_value": 432.00,
    "purchase_date": "2025-01-01",
    "purchase_document_guid": "doc-000016",
    "warranty_start_date": null,
    "warranty_end_date": null,
    "warranty_notify_days_before": 0
  },

  {
    "business_code": "DOC",
    "asset_label": "DOC-000017",
    "asset_sequence_number": 17,
    "category_id": 9,
    "status_definition_id": 1,
    "name": "Vertragsordner Einkauf",
    "description": "Digitalisierte Verträge",
    "manufacturer_id": 9,
    "supplier_number": "SUP1007",
    "supplier_name": "DocuWare",
    "supplier_address": "Planegger Str. 1",
    "supplier_post_code": "82110",
    "supplier_city": "Germering",
    "supplier_country": "Deutschland",
    "current_location_id": 6,
    "image_storage_key": "assets/doc-000017.jpg",
    "barcode_value": "100000017",
    "qr_value": "QR100000017",
    "purchase_value": 250.00,
    "purchase_date": "2024-10-10",
    "purchase_document_guid": "doc-000017",
    "warranty_start_date": null,
    "warranty_end_date": null,
    "warranty_notify_days_before": 0
  },

  {
    "business_code": "NB",
    "asset_label": "NB-000018",
    "asset_sequence_number": 18,
    "category_id": 1,
    "status_definition_id": 3,
    "name": "Dell Latitude 5520",
    "description": "Ausgemustert",
    "manufacturer_id": 1,
    "supplier_number": "SUP1001",
    "supplier_name": "Bechtle GmbH",
    "supplier_address": "Bechtle Platz 1",
    "supplier_post_code": "74172",
    "supplier_city": "Neckarsulm",
    "supplier_country": "Deutschland",
    "current_location_id": 9,
    "image_storage_key": "assets/nb-000018.jpg",
    "barcode_value": "100000018",
    "qr_value": "QR100000018",
    "purchase_value": 1199.00,
    "purchase_date": "2021-06-03",
    "purchase_document_guid": "doc-000018",
    "warranty_start_date": "2021-06-03",
    "warranty_end_date": "2024-06-02",
    "warranty_notify_days_before": 30
  },

  {
    "business_code": "NB",
    "asset_label": "NB-000019",
    "asset_sequence_number": 19,
    "category_id": 1,
    "status_definition_id": 1,
    "name": "Dell Latitude 5550",
    "description": "Notebook Management",
    "manufacturer_id": 1,
    "supplier_number": "SUP1001",
    "supplier_name": "Bechtle GmbH",
    "supplier_address": "Bechtle Platz 1",
    "supplier_post_code": "74172",
    "supplier_city": "Neckarsulm",
    "supplier_country": "Deutschland",
    "current_location_id": 2,
    "image_storage_key": "assets/nb-000019.jpg",
    "barcode_value": "100000019",
    "qr_value": "QR100000019",
    "purchase_value": 1699.00,
    "purchase_date": "2025-04-01",
    "purchase_document_guid": "doc-000019",
    "warranty_start_date": "2025-04-01",
    "warranty_end_date": "2028-03-31",
    "warranty_notify_days_before": 30
  },

  {
    "business_code": "NB",
    "asset_label": "NB-000020",
    "asset_sequence_number": 20,
    "category_id": 1,
    "status_definition_id": 1,
    "name": "Lenovo ThinkPad X1",
    "description": "Premium Notebook",
    "manufacturer_id": 2,
    "supplier_number": "SUP1001",
    "supplier_name": "Bechtle GmbH",
    "supplier_address": "Bechtle Platz 1",
    "supplier_post_code": "74172",
    "supplier_city": "Neckarsulm",
    "supplier_country": "Deutschland",
    "current_location_id": 1,
    "image_storage_key": "assets/nb-000020.jpg",
    "barcode_value": "100000020",
    "qr_value": "QR100000020",
    "purchase_value": 1999.00,
    "purchase_date": "2025-05-01",
    "purchase_document_guid": "doc-000020",
    "warranty_start_date": "2025-05-01",
    "warranty_end_date": "2028-04-30",
    "warranty_notify_days_before": 30
  },

  {
    "business_code": "MON",
    "asset_label": "MON-000021",
    "asset_sequence_number": 21,
    "category_id": 2,
    "status_definition_id": 1,
    "name": "LG UltraFine 27",
    "description": "Grafikmonitor",
    "manufacturer_id": 10,
    "supplier_number": "SUP1001",
    "supplier_name": "Bechtle GmbH",
    "supplier_address": "Bechtle Platz 1",
    "supplier_post_code": "74172",
    "supplier_city": "Neckarsulm",
    "supplier_country": "Deutschland",
    "current_location_id": 7,
    "image_storage_key": "assets/mon-000021.jpg",
    "barcode_value": "100000021",
    "qr_value": "QR100000021",
    "purchase_value": 549.00,
    "purchase_date": "2025-04-20",
    "purchase_document_guid": "doc-000021",
    "warranty_start_date": "2025-04-20",
    "warranty_end_date": "2028-04-19",
    "warranty_notify_days_before": 30
  },

  {
    "business_code": "PRN",
    "asset_label": "PRN-000022",
    "asset_sequence_number": 22,
    "category_id": 5,
    "status_definition_id": 2,
    "name": "Brother MFC-L8900",
    "description": "Multifunktionsgerät",
    "manufacturer_id": 11,
    "supplier_number": "SUP1003",
    "supplier_name": "Cancom GmbH",
    "supplier_address": "Erika-Mann-Str. 69",
    "supplier_post_code": "80636",
    "supplier_city": "München",
    "supplier_country": "Deutschland",
    "current_location_id": 8,
    "image_storage_key": "assets/prn-000022.jpg",
    "barcode_value": "100000022",
    "qr_value": "QR100000022",
    "purchase_value": 899.00,
    "purchase_date": "2023-11-15",
    "purchase_document_guid": "doc-000022",
    "warranty_start_date": "2023-11-15",
    "warranty_end_date": "2026-11-14",
    "warranty_notify_days_before": 60
  },

  {
    "business_code": "NET",
    "asset_label": "NET-000023",
    "asset_sequence_number": 23,
    "category_id": 8,
    "status_definition_id": 1,
    "name": "Aruba Access Point AP-635",
    "description": "WLAN Access Point",
    "manufacturer_id": 12,
    "supplier_number": "SUP1006",
    "supplier_name": "TD Synnex",
    "supplier_address": "Kistlerhofstraße 75",
    "supplier_post_code": "81379",
    "supplier_city": "München",
    "supplier_country": "Deutschland",
    "current_location_id": 5,
    "image_storage_key": "assets/net-000023.jpg",
    "barcode_value": "100000023",
    "qr_value": "QR100000023",
    "purchase_value": 599.00,
    "purchase_date": "2025-02-01",
    "purchase_document_guid": "doc-000023",
    "warranty_start_date": "2025-02-01",
    "warranty_end_date": "2030-01-31",
    "warranty_notify_days_before": 120
  },

  {
    "business_code": "NET",
    "asset_label": "NET-000024",
    "asset_sequence_number": 24,
    "category_id": 8,
    "status_definition_id": 1,
    "name": "Cisco ISR 4331",
    "description": "Standortrouter",
    "manufacturer_id": 6,
    "supplier_number": "SUP1006",
    "supplier_name": "TD Synnex",
    "supplier_address": "Kistlerhofstraße 75",
    "supplier_post_code": "81379",
    "supplier_city": "München",
    "supplier_country": "Deutschland",
    "current_location_id": 10,
    "image_storage_key": "assets/net-000024.jpg",
    "barcode_value": "100000024",
    "qr_value": "QR100000024",
    "purchase_value": 3400.00,
    "purchase_date": "2024-05-01",
    "purchase_document_guid": "doc-000024",
    "warranty_start_date": "2024-05-01",
    "warranty_end_date": "2029-04-30",
    "warranty_notify_days_before": 120
  },

  {
    "business_code": "SW",
    "asset_label": "SW-000025",
    "asset_sequence_number": 25,
    "category_id": 7,
    "status_definition_id": 1,
    "name": "Adobe Creative Cloud",
    "description": "Designer Lizenz",
    "manufacturer_id": 13,
    "supplier_number": "SUP1008",
    "supplier_name": "Adobe",
    "supplier_address": "Georg-Brauchle-Ring 58",
    "supplier_post_code": "80992",
    "supplier_city": "München",
    "supplier_country": "Deutschland",
    "current_location_id": 7,
    "image_storage_key": "assets/sw-000025.jpg",
    "barcode_value": "100000025",
    "qr_value": "QR100000025",
    "purchase_value": 719.88,
    "purchase_date": "2025-01-01",
    "purchase_document_guid": "doc-000025",
    "warranty_start_date": null,
    "warranty_end_date": null,
    "warranty_notify_days_before": 0
  },

  {
    "business_code": "DOC",
    "asset_label": "DOC-000026",
    "asset_sequence_number": 26,
    "category_id": 9,
    "status_definition_id": 1,
    "name": "Vertragsarchiv IT",
    "description": "Digitale Dokumentensammlung",
    "manufacturer_id": 9,
    "supplier_number": "SUP1007",
    "supplier_name": "DocuWare",
    "supplier_address": "Planegger Str. 1",
    "supplier_post_code": "82110",
    "supplier_city": "Germering",
    "supplier_country": "Deutschland",
    "current_location_id": 6,
    "image_storage_key": "assets/doc-000026.jpg",
    "barcode_value": "100000026",
    "qr_value": "QR100000026",
    "purchase_value": 250.00,
    "purchase_date": "2025-03-05",
    "purchase_document_guid": "doc-000026",
    "warranty_start_date": null,
    "warranty_end_date": null,
    "warranty_notify_days_before": 0
  },

  {
    "business_code": "SRV",
    "asset_label": "SRV-000027",
    "asset_sequence_number": 27,
    "category_id": 6,
    "status_definition_id": 1,
    "name": "SQL Server Cluster",
    "description": "Datenbankserver",
    "manufacturer_id": 1,
    "supplier_number": "SUP1004",
    "supplier_name": "Dell Technologies",
    "supplier_address": "Unterschweinstiege 10",
    "supplier_post_code": "60549",
    "supplier_city": "Frankfurt",
    "supplier_country": "Deutschland",
    "current_location_id": 10,
    "image_storage_key": "assets/srv-000027.jpg",
    "barcode_value": "100000027",
    "qr_value": "QR100000027",
    "purchase_value": 14500.00,
    "purchase_date": "2024-06-01",
    "purchase_document_guid": "doc-000027",
    "warranty_start_date": "2024-06-01",
    "warranty_end_date": "2029-05-31",
    "warranty_notify_days_before": 120
  },

  {
    "business_code": "SRV",
    "asset_label": "SRV-000028",
    "asset_sequence_number": 28,
    "category_id": 6,
    "status_definition_id": 1,
    "name": "Backup Server",
    "description": "Veeam Backup Infrastruktur",
    "manufacturer_id": 1,
    "supplier_number": "SUP1004",
    "supplier_name": "Dell Technologies",
    "supplier_address": "Unterschweinstiege 10",
    "supplier_post_code": "60549",
    "supplier_city": "Frankfurt",
    "supplier_country": "Deutschland",
    "current_location_id": 10,
    "image_storage_key": "assets/srv-000028.jpg",
    "barcode_value": "100000028",
    "qr_value": "QR100000028",
    "purchase_value": 6200.00,
    "purchase_date": "2024-06-01",
    "purchase_document_guid": "doc-000028",
    "warranty_start_date": "2024-06-01",
    "warranty_end_date": "2029-05-31",
    "warranty_notify_days_before": 120
  },

  {
    "business_code": "NET",
    "asset_label": "NET-000029",
    "asset_sequence_number": 29,
    "category_id": 8,
    "status_definition_id": 2,
    "name": "HP Aruba Switch 2930F",
    "description": "Access Switch",
    "manufacturer_id": 12,
    "supplier_number": "SUP1006",
    "supplier_name": "TD Synnex",
    "supplier_address": "Kistlerhofstraße 75",
    "supplier_post_code": "81379",
    "supplier_city": "München",
    "supplier_country": "Deutschland",
    "current_location_id": 5,
    "image_storage_key": "assets/net-000029.jpg",
    "barcode_value": "100000029",
    "qr_value": "QR100000029",
    "purchase_value": 1800.00,
    "purchase_date": "2022-08-21",
    "purchase_document_guid": "doc-000029",
    "warranty_start_date": "2022-08-21",
    "warranty_end_date": "2027-08-20",
    "warranty_notify_days_before": 120
  },

  {
    "business_code": "PHN",
    "asset_label": "PHN-000030",
    "asset_sequence_number": 30,
    "category_id": 3,
    "status_definition_id": 1,
    "name": "Apple iPhone 16 Pro",
    "description": "Management Smartphone",
    "manufacturer_id": 5,
    "supplier_number": "SUP1002",
    "supplier_name": "Telekom",
    "supplier_address": "Landgrabenweg 151",
    "supplier_post_code": "53227",
    "supplier_city": "Bonn",
    "supplier_country": "Deutschland",
    "current_location_id": 1,
    "image_storage_key": "assets/phn-000030.jpg",
    "barcode_value": "100000030",
    "qr_value": "QR100000030",
    "purchase_value": 1299.00,
    "purchase_date": "2025-04-15",
    "purchase_document_guid": "doc-000030",
    "warranty_start_date": "2025-04-15",
    "warranty_end_date": "2027-04-14",
    "warranty_notify_days_before": 60
  }
]

export const columns: ColumnDef<any>[] = [
  {
    accessorKey: 'asset_label',
    header: () => h('div', { class: 'font-medium'  }, 'Label'),
    cell: ({ row }) => {

      return h('div', {  }, row.getValue('asset_label'))
    },
  },
  {
    accessorKey: 'name',
    header: () => h('div', { class: 'font-medium' }, 'Name'),
    cell: ({ row }) => {
      return h('div', {  }, row.getValue('name'))
    },
  },
  {
    accessorKey: 'description',
    header: () => h('div', { class: 'font-medium' }, 'Beschreibung'),
    cell: ({ row }) => {
      return h('div', {  }, row.getValue('description'))
    },
  },
  {
    accessorKey: 'category',
    header: () => h('div', { class: 'font-medium' }, 'Kategorie'),
    cell: ({ row }) => {
      return h('div', {  }, row.getValue('category'))
    },
  },
  {
    accessorKey: 'name',
    header: () => h('div', { class: 'font-medium' }, 'Status'),
    cell: ({ row }) => {
      return h('div', {  }, row.getValue('name'))
    },
  },
  {
    accessorKey: 'name',
    header: () => h('div', { class: 'font-medium' }, 'Standort'),
    cell: ({ row }) => {
      return h('div', {  }, row.getValue('name'))
    },
  },
  {
    accessorKey: 'name',
    header: () => h('div', { class: 'font-medium' }, 'Hersteller'),
    cell: ({ row }) => {
      return h('div', {  }, row.getValue('name'))
    },
  },
  {
    accessorKey: 'name',
    header: () => h('div', { class: 'font-medium' }, 'Zugewiesen an'),
    cell: ({ row }) => {
      return h('div', {  }, row.getValue('name'))
    },
  },
  {
    accessorKey: 'warranty_end_date',
    header: () => h('div', { class: 'font-medium' }, 'Garantieende'),
    cell: ({ row }) => {
      return h('div', {  }, row.getValue('warranty_end_date'))
    },
  }
]
